const categoryKeys={formations:'domain',consultants:'tag',regulations:'category',clients:'sector'};
function categoryNames(section,source=data){return [...new Set([...(source.categories?.[section]||[]),...(source[section]||[]).map(item=>item[categoryKeys[section]]).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'fr'));}
function categorySettings(){
 const draft=JSON.parse(JSON.stringify(data));draft.categories??={};const host=$('#workspace');
 host.append(el('p',{},'Ajoutez, renommez ou supprimez les catégories de chaque collection. Renommer met à jour les fiches associées. Supprimer laisse les fiches sans catégorie. Enregistrez pour appliquer vos changements.'));
 for(const [section,key] of Object.entries(categoryKeys)){
  draft.categories[section]=categoryNames(section,draft);const panel=el('section',{class:'panel',style:'margin-bottom:16px'}),rows=el('div',{class:'fields'});
  panel.append(el('h2',{},labels[section]),rows);host.append(panel);
  function render(){rows.replaceChildren();for(const name of draft.categories[section]){
   const row=el('div',{class:'actions'}),input=el('input',{'aria-label':'Nom de catégorie : '+name});input.value=name;input.style.flex='1';
   row.append(input,el('span',{},draft[section].filter(item=>item[key]===name).length+' fiche(s)'),button('Renommer',()=>{const next=input.value.trim();if(!next||next===name)return;if(draft.categories[section].some(v=>searchKey(v)===searchKey(next))){status('Cette catégorie existe déjà.',true);return;}draft.categories[section]=draft.categories[section].map(v=>v===name?next:v);draft[section].forEach(item=>{if(item[key]===name)item[key]=next;});changed();render();}),button('Supprimer',()=>{if(!confirm('Supprimer cette catégorie ? Les fiches seront conservées sans catégorie.'))return;draft.categories[section]=draft.categories[section].filter(v=>v!==name);draft[section].forEach(item=>{if(item[key]===name)item[key]='';});changed();render();},'danger'));rows.append(row);
  }}
  render();const add=el('input',{'aria-label':'Nouvelle catégorie · '+labels[section],placeholder:'Nouvelle catégorie'});panel.append(add,button('Ajouter une catégorie',()=>{const name=add.value.trim();if(!name)return;if(draft.categories[section].some(v=>searchKey(v)===searchKey(name))){status('Cette catégorie existe déjà.',true);return;}draft.categories[section].push(name);add.value='';changed();render();}));
 }
 host.append(savebar(async()=>{const result=await api('data',{revision:dataRevision,data:draft});data=JSON.parse(JSON.stringify(draft));dataRevision=result.revision;}));
}
function categoryField(section,value,change){const wrap=el('label',{class:'field'}),select=el('select');wrap.append(el('span',{},fieldLabels[categoryKeys[section]]||'Catégorie'));select.append(el('option',{value:''},'Non classé'));categoryNames(section).forEach(name=>select.append(el('option',{value:name},name)));select.value=value||'';select.onchange=()=>{change(select.value);changed();};wrap.append(select,el('small',{},'Gérez les choix dans Paramètres · catégories.'));return wrap;}
function seoFields(parsed,host){
 let title=parsed.querySelector('title');if(!title){title=parsed.createElement('title');parsed.head.append(title);}
 host.append(field('Titre SEO',title.textContent,v=>title.textContent=v));
 for(const [attribute,key,label] of [['name','description','Description SEO'],['name','robots','Indexation (robots)'],['property','og:title','Titre du partage social'],['property','og:description','Description du partage social'],['property','og:image','Image du partage social'],['name','twitter:card','Format Twitter (ex. summary_large_image)']]){
  let node=parsed.head.querySelector('meta['+attribute+'="'+key+'"]');const value=node?.getAttribute('content')||'';
  const update=v=>{if(!v.trim()){node?.remove();node=null;return;}if(!node){node=parsed.createElement('meta');node.setAttribute(attribute,key);parsed.head.append(node);}node.setAttribute('content',v);};
  host.append(key==='og:image'?imageField(label,value,update):field(label,value,update,key.includes('description')));
 }
 let canonical=parsed.head.querySelector('link[rel="canonical"]');host.append(field('URL canonique',canonical?.getAttribute('href')||'',v=>{if(!v.trim()){canonical?.remove();canonical=null;return;}if(!canonical){canonical=parsed.createElement('link');canonical.rel='canonical';parsed.head.append(canonical);}canonical.setAttribute('href',v);}));
}
function seoPage(){const host=$('#workspace'),panel=el('section',{class:'panel'}),select=el('select',{'aria-label':'Page SEO'}),editor=el('div',{class:'fields'});select.append(el('option',{value:''},'Choisir une page'));inventory.pages.forEach(name=>select.append(el('option',{value:name},pageLabels[name]||name)));panel.append(el('h2',{},'Référencement des pages'),el('p',{},'Modifiez les informations enregistrées dans chaque page et utilisées par les moteurs de recherche et les réseaux sociaux.'),select,editor);host.append(panel);let current='';select.onchange=()=>{const next=select.value;select.value=current;guarded(errorBoundary(async()=>{current=next;select.value=current;dirty=false;editor.replaceChildren();if(!current)return;const name=current+'.html';let state=await api('document?name='+encodeURIComponent(name));const shared=[];const source=state.source.replace(/<!-- component:([\w-]+) -->[\s\S]*?<!-- \/component:\1 -->/g,block=>'<!-- SEO_SHARED_'+(shared.push(block)-1)+' -->');const parsed=new DOMParser().parseFromString(source,'text/html');seoFields(parsed,editor);if(current==='formation-detail')editor.append(el('p',{},'Le titre de chaque formation est généré à partir de son nom. Modifiez le nom dans Formations pour changer ce titre.'));editor.append(savebar(async()=>{let source='<!DOCTYPE html>\n'+parsed.documentElement.outerHTML;shared.forEach((block,i)=>source=source.replace('<!-- SEO_SHARED_'+i+' -->',block));state=await api('document',{name,source,revision:state.revision});}));}));};}
