'use strict';
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/admin/studio-overrides.css">');
const $=s=>document.querySelector(s);
const labels={dashboard:'Vue d’ensemble',pages:'Pages du site',components:'Composants partagés',formations:'Formations',consultants:'Consultants',regulations:'Réglementation',clients:'Clients & logos',media:'Images & médias'};
const pageLabels={index:'Accueil',formations:'Catalogue', 'formation-detail':'Détail d’une formation',services:'Services & audits',consultants:'Experts',reglementation:'Réglementation',simulateur:'Simulateur',contact:'Contact',header:'Menu & identité',navigation:'Liens de navigation',footer:'Pied de page','home-hero':'Accueil · introduction','mobile-dock':'Navigation mobile'};
const fieldLabels={title:'Titre',name:'Nom',domain:'Domaine',duration_days:'Durée en jours',duration_hours:'Durée en heures',public_cible:'Public cible',prerequis:'Prérequis',objectives:'Objectifs · une ligne par objectif',content:'Programme · une ligne par élément',certification:'Certification',attached_file:'Document associé',is_featured:'Mettre en avant',avatar:'Photo',image:'Image de la formation',image_alt:'Description de l’image',role:'Fonction',tag:'Badge',credentials:'Présentation',specialties:'Expertises · une ligne par expertise',pdf:'Lien PDF',description:'Description',bo:'Bulletin officiel',date:'Date',logo:'Logo',url:'Lien'};
let data, dataRevision, inventory, activeTab='dashboard',dirty=false,selection,documentState,mediaCallback,pendingLeave;
function el(tag,attrs={},text) { const node=document.createElement(tag); for(const [key,value] of Object.entries(attrs)) { if(key==='class') node.className=value; else node.setAttribute(key,value); } if(text!==undefined) node.textContent=text; return node; }
function button(text,fn,cls='') {const b=el('button',{type:'button',class:cls},text);b.addEventListener('click',fn);return b;}
function status(message,error=false) {$('#status').textContent=message;$('#status').className=error?'error':'';}
async function api(route,body) {const response=await fetch('/api/editor/'+route,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw new Error(result.error||'Une erreur est survenue.');return result;}
function changed(){dirty=true;const state=$('#save-state');if(state)state.textContent='Modifications non enregistrées';}
function guarded(fn){if(!dirty){fn();return;}pendingLeave=fn;$('#leave-dialog').showModal();}
function errorBoundary(fn){return async()=>{try{await fn();}catch(error){status(error.message,true);}};}
function field(label,value,onChange,multiline=false){const wrap=el('label',{class:'field'});wrap.append(el('span',{},label));const input=el(multiline?'textarea':'input');if(!multiline)input.type='text';input.value=value??'';input.addEventListener('input',()=>{onChange(input.value);changed();});wrap.append(input);return wrap;}
function savebar(save){const bar=el('div',{class:'savebar'});bar.append(el('span',{id:'save-state'},'Aucune modification en attente'));const b=button('Enregistrer les modifications',async()=>{b.disabled=true;try{await save();dirty=false;$('#save-state').textContent='Modifications enregistrées';status('Enregistré. Vos modifications sont visibles sur le site.');}catch(e){status(e.message,true);}finally{b.disabled=false;}},'primary');bar.append(b);return bar;}
function previewLink(url){return el('a',{href:url,target:'_blank',rel:'noopener',class:'button'},'Voir la page ↗');}
function imageField(label,value,change){const wrap=el('div',{class:'field-image'});const img=el('img',{alt:'Aperçu de l’image'});function update(v){img.src=v?new URL(v,location.origin+'/').href:'';change(v);}img.src=value?new URL(value,location.origin+'/').href:'';const input=field(label,value,v=>update(v));wrap.append(img,input,button('Choisir une image',()=>openMedia(url=>{input.querySelector('input').value=url;update(url);changed();})));return wrap;}
function renderNavigation(){const nav=$('#navigation');nav.replaceChildren();Object.entries(labels).forEach(([key,label])=>{const b=button(label,()=>guarded(()=>showTab(key)));if(key===activeTab)b.setAttribute('aria-current','page');nav.append(b);});}
async function showTab(tab){activeTab=tab;selection=null;dirty=false;$('#title').textContent=labels[tab];$('#subtitle').textContent=tab==='components'?'Une modification se répercute sur toutes les pages.':tab==='pages'?'Modifiez les textes, liens et images de chaque page.':'Votre contenu, organisé et toujours à jour.';$('#navigation').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');renderNavigation();$('#workspace').replaceChildren();status('');if(tab==='dashboard')dashboard();else if(tab==='media')await mediaPage();else editorList();}
function dashboard(){const host=$('#workspace');const intro=el('section',{class:'panel welcome'});intro.append(el('p',{class:'eyebrow'},'BIENVENUE DANS VOTRE STUDIO'),el('h2',{},'Un espace clair pour faire évoluer votre site.'),el('p',{},'Actualisez vos pages, enrichissez vos formations et choisissez les images qui racontent votre expertise.'));const actions=el('div',{class:'actions'});actions.append(button('Modifier une page',()=>showTab('pages'),'primary'),button('Explorer les images',()=>showTab('media')));intro.append(actions);host.append(intro);const cards=el('div',{class:'cards'});for(const [number,title] of [[inventory.pages.length,'Pages du site'],[data.formations.length,'Formations'],[inventory.components.length,'Composants partagés'],[data.consultants.length,'Experts']]){const card=el('div',{class:'card'});card.append(el('strong',{},number),el('small',{},title));cards.append(card);}host.append(cards);const note=el('section',{class:'panel',style:'margin-top:24px'});note.append(el('h2',{},'Comment modifier votre site ?'),el('p',{},'Choisissez une page pour ses contenus propres. Utilisez « Composants partagés » pour le menu, le pied de page et l’introduction de l’accueil. Les fiches de formation et profils sont gérés dans leurs collections.'),el('p',{},'Les images importées restent disponibles dans la médiathèque. Enregistrez pour appliquer vos changements.'));host.append(note);}
function editorList(){const host=$('#workspace');const layout=el('div',{class:'editor-layout'}),left=el('section',{class:'panel'}),search=el('input',{type:'search',placeholder:'Rechercher…','aria-label':'Rechercher un contenu'}),list=el('div',{class:'item-list'}),right=el('section',{class:'panel',id:'editor'});right.append(el('p',{class:'empty'},'Choisissez un contenu à modifier.'));left.append(search,list);layout.append(left,right);host.append(layout);const collection=activeTab==='pages'?inventory.pages:activeTab==='components'?inventory.components:data[activeTab];function render(){list.replaceChildren();collection.forEach((entry,index)=>{const title=typeof entry==='string'?(pageLabels[entry]||entry):(entry.title||entry.name||entry.id||'Élément '+(index+1));if(!title.toLowerCase().includes(search.value.toLowerCase()))return;const row=el('div',{class:'item-row'});const b=button(title,()=>guarded(errorBoundary(async()=>{selection=index;list.querySelectorAll('button.item-select').forEach(n=>n.classList.remove('selected'));b.classList.add('selected');if(typeof entry==='string')await documentEditor(activeTab==='pages'?entry+'.html':'components/'+entry+'.html',title);else recordEditor(entry,title);})), 'item-select');row.append(b);if(typeof entry!=='string')row.append(button('Supprimer',()=>guarded(errorBoundary(()=>deleteRecord(index,title))), 'danger small'));list.append(row);});}search.addEventListener('input',render);render();}
async function deleteRecord(index,title){if(!confirm(`Supprimer « ${title} » définitivement ?`))return;const result=await api('data-delete',{collection:activeTab,index,revision:dataRevision});data=result.data;dataRevision=result.revision;selection=null;status(`« ${title} » a été supprimé.`);editorList();}
async function documentEditor(name,title){documentState=await api('document?name='+encodeURIComponent(name));const host=$('#editor');host.replaceChildren();const head=el('div',{class:'editor-head'});head.append(el('h2',{},title),previewLink(name.startsWith('components/')?'/index.html':'/'+name));host.append(head);const shared=[];const clean=documentState.source.replace(/<!-- component:([\w-]+) -->[\s\S]*?<!-- \/component:\1 -->/g,block=>{const index=shared.push(block)-1;return `<!-- STUDIO_SHARED_${index} -->`;});const full=!name.startsWith('components/');const parsed=new DOMParser().parseFromString(clean,'text/html');
function serialize(){let source=full?'<!DOCTYPE html>\n'+parsed.documentElement.outerHTML:parsed.body.innerHTML;shared.forEach((block,i)=>{source=source.replace(`<!-- STUDIO_SHARED_${i} -->`,block);});return source;}
const search=el('input',{type:'search',placeholder:'Filtrer les champs…','aria-label':'Filtrer les champs de la page'});host.append(search);const sections=el('div');host.append(sections);
const groups={};for(const title of ['Textes','Liens & boutons','Images','Métadonnées']){const group=el('details',{open:''});group.append(el('summary',{},title));const fields=el('div',{class:'fields'});group.append(fields);groups[title]=fields;sections.append(group);}
const walker=parsed.createTreeWalker(parsed.body,NodeFilter.SHOW_TEXT);let node,count=0;while(node=walker.nextNode()){const current=node,parent=current.parentElement;if(!current.textContent.trim()||parent.closest('script,style,noscript,svg')||current.textContent.includes('{{'))continue;const text=current.textContent.trim();const label=(parent.closest('h1,h2,h3,h4')?'Titre':'Texte')+' '+(++count);groups.Textes.append(field(label,text,value=>{current.textContent=value;},text.length>100));}
parsed.querySelectorAll('a[href],button,input[placeholder],textarea[placeholder]').forEach(node=>{if(node.matches('a')){const label=node.textContent.trim().slice(0,90)||'Lien';groups['Liens & boutons'].append(field(label,node.getAttribute('href'),v=>node.setAttribute('href',v)));}if(node.hasAttribute('placeholder'))groups['Liens & boutons'].append(field('Texte indicatif',node.getAttribute('placeholder'),v=>node.setAttribute('placeholder',v)));if(node.hasAttribute('aria-label'))groups['Liens & boutons'].append(field('Libellé accessible',node.getAttribute('aria-label'),v=>node.setAttribute('aria-label',v)));});
parsed.querySelectorAll('img').forEach((node,i)=>{const wrap=el('div');wrap.append(imageField('Image '+(i+1),node.getAttribute('src'),url=>node.setAttribute('src',url)),field('Description de l’image',node.getAttribute('alt'),v=>node.setAttribute('alt',v)));groups.Images.append(wrap);});
if(full){const titleNode=parsed.querySelector('title');if(titleNode)groups['Métadonnées'].append(field('Titre dans le navigateur',titleNode.textContent,v=>titleNode.textContent=v));const meta=parsed.querySelector('meta[name=description]');if(meta)groups['Métadonnées'].append(field('Description pour les moteurs de recherche',meta.content,v=>meta.content=v,true));}
for(const fields of Object.values(groups))if(!fields.children.length)fields.parentElement.remove();
search.addEventListener('input',()=>{const q=search.value.toLowerCase();sections.querySelectorAll('label.field').forEach(label=>{label.hidden=!(label.textContent+' '+label.querySelector('input,textarea')?.value).toLowerCase().includes(q);});});
if(shared.length)host.append(el('p',{},'Le menu, le pied de page et les autres blocs partagés se modifient dans « Composants partagés ». Les contenus automatiques se modifient dans leurs collections.'));
host.append(savebar(async()=>{const saved=await api('document',{name,revision:documentState.revision,source:serialize()});documentState=saved;}));}
function recordEditor(record,title){const host=$('#editor');host.replaceChildren();const draft=JSON.parse(JSON.stringify(record));if(activeTab==='formations'){draft.image??='';draft.image_alt??='';}const head=el('div',{class:'editor-head'});head.append(el('h2',{},title));if(activeTab==='formations')head.append(previewLink('/formation-detail.html?id='+encodeURIComponent(record.id)));host.append(head);const fields=el('div',{class:'fields'});host.append(fields);function renderObject(obj,container,prefix=''){for(const [key,value] of Object.entries(obj)){const label=fieldLabels[key]||key;if(key==='id'){container.append(el('small',{},'Identifiant : '+value));continue;}if(typeof value==='boolean'){const l=el('label',{class:'field'}),input=el('input',{type:'checkbox'});input.checked=value;input.addEventListener('change',()=>{obj[key]=input.checked;changed();});l.append(el('span',{},label),input);container.append(l);}else if(Array.isArray(value)&&value.every(v=>typeof v==='string'))container.append(field(label,value.join('\n'),v=>obj[key]=v.split('\n').filter(s=>s.trim()),true));else if(value&&typeof value==='object'){const d=el('details',{open:''});d.append(el('summary',{},label));const c=el('div',{class:'fields'});renderObject(value,c,prefix+key+'.');d.append(c);container.append(d);}else if(['image','avatar','logo'].includes(key))container.append(imageField(label,value,v=>obj[key]=v));else container.append(field(label,value,v=>obj[key]=typeof value==='number'?Number(v):v,String(value||'').length>100));}}
renderObject(draft,fields);const actions=el('div',{class:'actions editor-actions'});actions.append(button('Supprimer cet élément',()=>guarded(errorBoundary(()=>deleteRecord(selection,title))),'danger'));host.append(actions,savebar(async()=>{const next=JSON.parse(JSON.stringify(data));next[activeTab][selection]=draft;const saved=await api('data',{revision:dataRevision,data:next});data=next;dataRevision=saved.revision;Object.assign(record,draft);}));}
async function fillMedia(container,pick){const {images}=await api('media');container.replaceChildren();for(const image of images){const tile=el('div',{class:'media-tile'});const b=button('',()=>pick(image.url),'media-pick');b.append(el('img',{src:image.url,alt:image.name,loading:'lazy'}),el('span',{},image.name),el('small',{},Math.round(image.size/1024)+' Ko'));tile.append(b,button('Supprimer',async()=>{if(!confirm(`Supprimer « ${image.name} » définitivement ?`))return;try{await api('media-delete',{url:image.url});status(`« ${image.name} » a été supprimé.`);await fillMedia(container,pick);}catch(e){status(e.message,true);}},'danger small'));container.append(tile);}if(!images.length)container.append(el('p',{},'Aucune image disponible.'));}
async function openMedia(callback){mediaCallback=callback;$('#media-status').textContent='';$('#media-dialog').showModal();try{await fillMedia($('#media-grid'),url=>{mediaCallback(url);$('#media-dialog').close();});}catch(e){$('#media-status').textContent=e.message;}}
async function mediaPage(){const host=$('#workspace');const panel=el('section',{class:'panel'});panel.append(el('h2',{},'Votre bibliothèque visuelle'),el('p',{},'Importez vos visuels, puis sélectionnez-les dans les pages, composants ou fiches de formation.'),button('Importer / choisir une image',()=>openMedia(url=>{status('Image disponible : '+url);mediaPage();}),'primary'));const grid=el('div',{class:'media-grid'});panel.append(grid);host.replaceChildren(panel);await fillMedia(grid,url=>{window.open(url,'_blank','noopener');});}
$('#upload').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw new Error('Image limitée à 10 Mo.');$('#media-status').textContent='Importation…';const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});const result=await api('upload',{base64});$('#media-status').textContent='Image importée.';mediaCallback(result.url);$('#media-dialog').close();}catch(e){$('#media-status').textContent=e.message;}finally{event.target.value='';}});
$('#close-media').onclick=()=>$('#media-dialog').close();$('#stay').onclick=()=>$('#leave-dialog').close();$('#discard').onclick=()=>{dirty=false;$('#leave-dialog').close();pendingLeave?.();};$('#menu').onclick=()=>{const open=$('#navigation').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));};
function theme(dark){document.body.classList.toggle('dark',dark);$('#theme').textContent=dark?'☀ Mode clair':'☾ Mode sombre';$('#theme').setAttribute('aria-label',dark?'Activer le mode clair':'Activer le mode sombre');}theme(localStorage.getItem('meplus_admin_theme')==='dark');$('#theme').onclick=()=>{const dark=!document.body.classList.contains('dark');theme(dark);localStorage.setItem('meplus_admin_theme',dark?'dark':'light');};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
(async()=>{try{const result=await api('data');data=result.data;dataRevision=result.revision;inventory=await api('inventory');await showTab('dashboard');}catch(e){status('Impossible de charger le studio : '+e.message,true);$('#workspace').replaceChildren(button('Réessayer',()=>location.reload()));}})();
